### ISSUE TITLE
About Algorithm 1

### ISSUE THREAD

**Issue by vv123infinity** [Decadz/Sparse-Label-Smoothing-Regularization#1]
In Algorithm 1 of that paper, I interpreted S meta as the number of outer loops and S base as the number of inner loops. I would like to know why the position of the statement X_j, y_j ← Sample Task T_j ~ p(T) is inside the inner loop. This is somewhat inconsistent with MAML thinking.

**Comment by Decadz** [comment]
Hi,

Regarding the task sampling line in Algorithm 1 in the EvoMAL paper, this is algorithmically equivalent to how sampling is done in MAML. 

---

**EvoMAL**: In my psudocode I say to sample a new task (_singular_) at each step in the inner optimization (where each inner optimization has a trajectory length = 1).

$X_j, y_j \leftarrow \text{Sample Task } T_j \sim p(T)$,

---

**MAML**: In their psudocode they say to sample a batch of tasks (_plural_) upfront, and then pass it to the inner optimization where each inner optimization trajectory (of length >= 1) is on a new task.

$\text{Sample batch of tasks } T_i ∼ p(T)$,

---

Please let me know if there is any further confusion or questions.

Cheers,
Christian

**Comment by vv123infinity** [comment]
> Hi,
> 
> Regarding the task sampling line in Algorithm 1 in the EvoMAL paper, this is algorithmically equivalent to how sampling is done in MAML.
> 
> **EvoMAL**: In my psudocode I say to sample a new task (_singular_) at each step in the inner optimization (where each inner optimization has a trajectory length = 1).
> 
> X j , y j ← Sample Task  T j ∼ p ( T ) ,
> 
> **MAML**: In their psudocode they say to sample a batch of tasks (_plural_) upfront, and then pass it to the inner optimization where each inner optimization trajectory (of length >= 1) is on a new task.
> 
> Sample batch of tasks  T i ∼ p ( T ) ,
> 
> Please let me know if there is any further confusion or questions.
> 
> Cheers, Christian

Thank you for your reply! Exactly, the paper states that you fixed the value of S base to 1. I considered the case where S base > 1, so I posed the question to you. If the value of S base is fixed to 1, then no problem. Thanks again for your reply!😁

**Comment by Decadz** [comment]
No worries, im glad my response helped :)
